name: 'Jogoa | Brandstories & Content Marketing'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64558
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: 'Van strategie naar het bouwen van brand stories; het verhaal rondom je merk waarmee we consumenten, prospects en klanten kunnen inspireren en binden.  Mijn associates en ik helpen organisaties op een pragmatische manier hun marketing te versnellen. Door eerst scherp te positioneren en vervolgens met op persona geijkte customer journeys te zorgen voor een optimale merkbeleving ondersteund door slimme marketingautomatisering.  Met een continu content marketing programma zorgen we vervolgens voor een constante aanwas van nieuwe contacten en trouwe klanten'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#F9F8F6'
    - '#564B4B'
    - '#D9D2CC'
    - '#998E88'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
